### PR TITLE
[simulation] Fix multiproject Gradle support problems

### LINKED ISSUE #687: Inconsistent simulation builds
**Describe the bug**
When running `./gradlew simulateNativeDebug`  I get inconsistent results with the same code. 

**To Reproduce**
1. run `git clone https://github.com/spacey-sooty/2024-Crescendo.git`
2. run `cd 2024-Crescendo`
3. run `./gradlew simulateNativeDebug`
4. See this error message
```
> Task :wombat:simulateNativeDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wombat:simulateNativeDebug'.
> Must have 1 and only 1 binary

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 16s
3 actionable tasks: 3 executed
```
6.  run `./gradlew build` (succeeds)
7. run `./gradlew simulateNative`
8. See this error message
```
> Task :wombat:simulateNativeRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wombat:simulateNativeRelease'.
> Must have 1 and only 1 binary

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 12s
6 actionable tasks: 2 executed, 4 up-to-date
```
9. repeat steps 7 and 8 once.
10. run `./gradlew simulateNativeDebug`
11. Success

 - Link to code: https://github.com/spacey-sooty/2024-Crescendo/tree/master

**Expected behavior**
I expect when I simulate my project with no changes to it the result is the same.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.2
 - Project Information: 
Screenshot from 2023-11-24 11-58-37

### PR DESCRIPTION
**Pull request by spacey-sooty**
Fixes #687

### CODE REVIEW

**Comment by ThadHouse** [comment]
This won't actually work. Your project is hitting the case where 0 binaries are specified. And we don't want to make that just be silently ignored.

**Comment by ThadHouse** [comment]
It's the `wpi.cpp.enableExternalTasks(it)` in the binary definition that adds the binary to the simulation task.

**Comment by spacey-sooty** [comment]
Yeah I started testing it and I realised this. I've made another change to improve the error message a bit.

**Comment by spacey-sooty** [comment]
@ThadHouse maybe if we see you only have non executable binaries we print that out as a warning and peacefully exit at that point?

**Comment by ThadHouse** [comment]
Thats not the issue. Currently, the task is created automatically whenever the gradlerio plugin is applied. It is then up to the project to explicitly add a binary to the simulation task. Thats what the call to `wpi.cpp.enableExternalTasks(it)` in the binary definition does. The sim task doesn't attempt to automatically add any binaries, and doesn't have access to do that either. 

Basically the way to solve this would be to only create the sim tasks if `wpi.cpp.enableExternalTasks(it)` is called, instead of eagerly creating them, as happens currently.

**Pull request closed without merging**
