### PR TITLE
RoboRIO Image Version is hard-coded Issue

### PR DESCRIPTION
**Pull request by Team3840**
**GradleRIO/src/main/groovy/edu/wpi/first/gradlerio/frc/RoboRIO.groovy**
With the new version NI Beta release 2 it fails to deploy code because of image version mismatch.
 
Change List<String> validImageVersions = ['2019_v4'] to
List<String> validImageVersions = ['2019_v*']

Making the List<String> validImageVersions = ['2019_v4'] to be a wild card for the 2019 season. ['2019_v*']
This would prevent exceptions being thrown during image changes during Beta testing and season from NI

gradle and image issue
.

### CODE REVIEW

**Comment by PeterJohnson** [comment]
The hardcoded version is intentional, as there are non-backwards-compatible library dependencies between wpilib and the libraries in the image (e.g. specific versions of wpilib will only work with specific image versions).  We are in the process of releasing beta 2 of wpilib.

**Comment by Team3840** [comment]
Thanks. I understand the reason why.  But I guess it would be nice to have the releases together so Beta testers are not left will image that is unusable until new release comes.

**Comment by JacisNonsense** [comment]
FWIW, the version numbers can be edited from the build.gradle, or just `checkImage = false` to bypass it entirely. It's not recommended at all, but is there for precisely the scenario you've described with the beta releases

**Comment by ThadHouse** [comment]
Do note that does not work for all images. The change from beta 1 to beta 2 is not compatible and will result in linking and runtime errors if the image is changed from beta 1 to beta 2

**Pull request closed without merging**
