### PR TITLE
Add `wpi.deps.vendor.folderpath` as mutable property

### LINKED ISSUE #432: Allow users to specify a custom vendordeps folder location
I have run into an issue with many projects, where my team uses multi-project gradle builds for everything. GradleRIO is requiring us to have a copy of our vendordeps folder in every single subproject.

Would someone be able to add a small flag or method somewhere that we can call to make the plugin use a different directory? (For example, we would use `rootProject.file("vendordeps")` instead of `project.file("vendordeps")`)

I am currently stuck with adding a copy task at the very start of the gradle task graph, and relying on it to copy the files around to every subproject.

### PR DESCRIPTION
**Pull request by Starlight220**
Resolves #432
 
@ThadHouse - the warning message probably needs some rewording/reworking, any ideas? And I couldn't find other locations of the "default-or-warning" part, feel free to point me in the direction of one to imitate.

### CODE REVIEW

**Comment by prateekma** [comment]
Here is an example: https://github.com/wpilibsuite/GradleRIO/pull/287

**Review by Ewpratten — DISMISSED** [review]

**Comment by Starlight220** [comment]
Other than the logging itself (which I'll fix soon), does how "default-or-warning" was handled in 287 have an advantage over the way I did it here?

**Review by Ewpratten — APPROVED** [review]

**Comment by Starlight220** [comment]
I manually tested this, with these cases:
- [x] As default: correctly finds files, doesn't print a warning  **{ expected behavior }**
- [x] Variable set to a nonexistent path: prints a warning, compile error (due to unresolved refs)  **{ expected behavior }**
- [x] Variable set to an existent path: prints a warning, successful compilation  **{ expected behavior }**
- [x] Variable set to default (`vendordeps`): doesn't print, successful compilation **{ expected behavior }**

All these are through the `gradle.properties` file, haven't tested DSL config (but based on [this comment](https://github.com/wpilibsuite/GradleRIO/pull/287#issuecomment-451694922) I would say that it shouldn't be accessed from there and therefore doesn't need to be tested).

**Comment by Starlight220** [comment]
@Ewpratten do you want to confirm that this works per your use case?
To use a dev version of GR:
- clone my branch
- bump the version
- publish to maven local (`./gradlew publishToMavenLocal` or similar)
- use the bumped version in your project

**Comment by Ewpratten** [comment]
I have already, and it is what I am looking for :+1:

**Review by ThadHouse — APPROVED** [review]

**Pull request merged**
