### PR TITLE
Use "exec" in robotCommand so the shell process goes away

### PR DESCRIPTION
**Pull request by PeterJohnson**

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Do you want to move that string to a common location so it's not duplicated?

**Comment by PeterJohnson** [comment]
“Exec”?  That seems overkill to me.

**Comment by JLLeitschuh** [comment]
I was referring to the whole line, they are duplicates of one another. Don't feel obligated to do so.

**Comment by ThadHouse** [comment]
It's very possible these would need to be different at some point in the future, so definitely don't want these combined.

**Comment by JacisNonsense** [comment]
Should we instead have this be part of the `robotCommand` stored in `FRCNativeArtifact` and `FRCJavaArtifact`, such that it can be overridden if that behaviour is desirable?

**Pull request closed without merging**
