### PR TITLE
Expand InvalidImageException message

### LINKED ISSUE #302: Better image out of date message.

### PR DESCRIPTION
**Pull request by Starlight220**
Fixes #302 
@Daltz333 do you think a different frc-docs article should be linked, or the link should not be to `/latest/`?

I don't like that the URL isn't in on one line in the source code, but without wrapping it passes the 100 char line limit.

Thoughts?

### CODE REVIEW

**Comment by Daltz333** [comment]
It should be /stable/.

**Comment by Starlight220** [comment]
Yeah, but `/stable/` doesn't have the 0-Robot yet, causing the link to 404.

**Comment by Daltz333** [comment]
Link to the original stable article and it will redirect

**Comment by sciencewhiz** [comment]
The message about reimaging to the latest firmware is misleadingly simplistic. Someone could have reimaged to the latest firmware and not have upgraded their project to a gradlerio version that is compatible. They may also not have a wpilib install that's compatible (ie old year)

A review of 10 threads on chiefdelphi show that in 6 of them the the roborio was the latest version but the project was old and in 4 of them the project was newer then the roborio version. 

Rather then trying to account for all these contingencies in a gradlerio error message it would be better to have a set of troubleshooting steps on frc-docs and then link to that.

**Comment by Starlight220** [comment]
How about something like this:
```
Invalid RoboRIO Image Version!
RoboRIO firmware and GradleRIO versions are incompatible:
   Current firmware version: <current version>
   GradleRIO-compatible versions: [<gradlerio-compatible versions>]
See <frc-docs link> for information about upgrading RoboRIO firmware and/or GradleRIO.
```

**Comment by Daltz333** [comment]
That looks pretty good. I'm not sure how well the newlines will be preserved.

**Comment by Starlight220** [comment]
The newlines will be preserved with `\n`, I think it'll be fairly effective. 
@Daltz333 should the link still point to https://docs.wpilib.org/en/stable/docs/getting-started/getting-started-frc-control-system/imaging-your-roborio.html or somewhere else now that it'll be the major source of information about this?

**Comment by Starlight220** [comment]
Can someone pls rerun the pipeline? It fails for an unrelated reason.

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
