### PR TITLE
Replace ScriptBase.sh with ScriptBase.py

### PR DESCRIPTION
**Pull request by calcmogul**

### CODE REVIEW

**Review by ThadHouse — DISMISSED** [review]

**Comment by ThadHouse** [comment]
https://github.com/calcmogul/GradleRIO/blob/update-scriptbase/src/main/groovy/edu/wpi/first/gradlerio/wpi/dependencies/tools/ToolRunTask.groovy

This file needs to be updated too

**Comment by Starlight220** [comment]
Why are we leaving the Windows version as is (if UNIX is using python, why not Windows too?)?
If both platforms use python, is platform separation (in plugin logic) needed?

**Comment by calcmogul** [comment]
Windows uses .vbs, not .py.

**Comment by Starlight220** [comment]
My question was to why not use the same script(ing language) for both platforms. Why can't we migrate to Python on Windows too?

**Comment by calcmogul** [comment]
Python isn't available by default on Windows, but it is on Ubuntu and macOS.

**Comment by Starlight220** [comment]
Oh ok, good to know.

**Review by PeterJohnson — APPROVED** [review]

**Pull request merged**
