### PR TITLE
Remove Kotlin tests

### PR DESCRIPTION
**Pull request by spacey-sooty**
Kotlin appears to work, still need to get JNI done

### CODE REVIEW

**Comment by ThadHouse** [comment]
Can you split out Kotlin from JNI? I'd be inclined to merge the JNI one, but have a lot more qualms about the Kotlin one.

**Comment by spacey-sooty** [comment]
> Can you split out Kotlin from JNI? I'd be inclined to merge the JNI one, but have a lot more qualms about the Kotlin one.

I'll split them out and leave this one as Kotlin as I managed to get that one working

**Comment by ThadHouse** [comment]
Based on the rest of the kotlin discussion, I'm inclined to say no to this.

**Comment by spacey-sooty** [comment]
> Based on the rest of the kotlin discussion, I'm inclined to say no to this.

Fair I've changed this to remove it instead

**Review by PeterJohnson — APPROVED** [review]

**Pull request closed without merging**
