### PR TITLE
Add clearFiles project property

### PR DESCRIPTION
**Pull request by KangarooKoala**
Let me know if I missed something obvious, I hadn't looked much at the GradleRIO project before.

### CODE REVIEW

**Review by spacey-sooty — COMMENTED** [review]
This should definitely be documented under gradlew tasks on frc-docs if its done like this.

**Comment by KangarooKoala** [comment]
That would be a nice way to do it, but at first glance I didn't find an easy way to get a task that has access to the `DeployContext`, but if I have more time hopefully I'd find a cleaner way. (I also should double-check it works...)

**Comment by spacey-sooty** [comment]
This would close https://github.com/wpilibsuite/deploy-utils/issues/24

**Comment by ThadHouse** [comment]
This is being done in more of an rsync style in https://github.com/wpilibsuite/deploy-utils/pull/31. Closing.

**Pull request closed without merging**
